### ISSUE TITLE
Option of "View COBOL Control Flow" does not appear on the  context menu

### ISSUE THREAD

**Issue by me00266** [BroadcomMFD/cobol-control-flow#1]
Hello,
after installing the extention Cobol Control Flow and following the instructions, the option of "View COBOL Control Flow" does not appear ont the context menu;
In terms of configurations on VSC, I've:

java 14.0.1
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:02:06.629Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Thank you in advance,
joao

**Comment by pd891575** [comment]
If you have IBM Z Open Editor installed, that will cause Cobol Control Flow to not appear in the context menu.  Also check that you are opening a cobol type program with extension cob or cbl.

**Comment by venkatzhub** [comment]
@pd891575  - yep, the View COBOL control flow menu item appears with the COBOL Language support extension from VSCode marketplace: https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support

**Comment by me00266** [comment]
I've disabled IBM Z Open Editor and it started to started to appear.
Is there a specific reason to not appear ?

joao

**Comment by venkatzhub** [comment]
@me00266  - the COBOL Language support extension and IBM Z Open Editor are two different implementations for the COBOL editor support. The COBOL Language support extension is open source, IBM Z Open Editor is not. The menu item contribution for the Control flow is from the Open source implementation as it is open.
