### ISSUE TITLE
"View COBOL Control Flow" not added to Context Menu

### ISSUE THREAD

**Issue by saisomu4somu** [BroadcomMFD/cobol-control-flow#10]
Hello 

Installed this extension newly. I'm not able to see "View COBOL Control  Flow" option when we right click (Refer below snapshot). 

![image](https://user-images.githubusercontent.com/34907289/98125532-98c9d500-1eda-11eb-83a4-0e675503a406.png)

Below is the snapshot of vscode. Any help in this regard is much appreciated.

![image](https://user-images.githubusercontent.com/34907289/98125886-f65e2180-1eda-11eb-8b2b-80b7a8d7ff45.png)

Thanks
Soma

**Comment by saisomu4somu** [comment]
Just found this extension not working if "IBM Z Open Editor" extension is installed. Once I uninstalled "IBM Z Open Editor" extension, able to see "View COBOL Control  Flow" option in context menu.

Can experts confirm if this is expected behavior.

**Comment by zimlu02** [comment]
> Just found this extension not working if "IBM Z Open Editor" extension is installed. Once I uninstalled "IBM Z Open Editor" extension, able to see "View COBOL Control Flow" option in context menu.
> 
> Can experts confirm if this is expected behavior.

Hi Soma,

we were trying to identify possible reasons of your problem before replying back but what you have found makes perfect sense. It is a known issue that "IBM Z Open Editor" extension is blocking or interfering with our plugins and there is nothing we can do about it from our side. We suggest keeping installed extensions only from one provider.

Thank you!

**Comment by saisomu4somu** [comment]
Thanks a lot @zimlu02
