### ISSUE TITLE
Open-source?

### ISSUE THREAD

**Issue by OlegKunitsyn** [BroadcomMFD/cobol-control-flow#12]
Please consider to open the source-code of the tool. The openness 
- shares maintenance expenses with the community,
- makes development more intensive,
- rewards the authors of the dependencies,
- inspires successors.

Open ANTLR files will help develop new tools for Enterprise COBOL ecosystem:
- CobolLexer.g4
- CobolParser.g4

Dependencies in use:
- @babel/cli: MIT
- @babel/core: MIT
- @babel/preset-env: MIT
- antlr4ts: BSD-3-Clause
- antlr4ts-cli: antlr4ts-cli
- codemirror: MIT
- d3: BSD-3-Clause
- del-cli: MIT
- jest: MIT
- jest-fetch-mock: MIT
- jquery: MIT
- lodash: MIT
- node-fetch: MIT
- npm-run-all: MIT
- react: MIT
- react-dom: MIT
- react-scripts: MIT
- service-worker-mock: MIT
- sinon: BSD-3-Clause
- ts-jest: MIT
- ts-loader: MIT
- ts-mock-imports: MIT
- tslint: Apache-2.0
- typescript: Apache-2.0
- typescript-string-operations: MIT
- vscode-extension-telemetry: MIT
- webpack-cli: MIT

**Comment by GitMensch** [comment]
I second that, but have to note that this is a follow-up to the closed issue #8.

> We came to the conclusion that for the time being, we won't open-source this project.


Note: antlr4ts-cli is BSD-3, too.

And for the 4 BSD-3 clause dependencies which state:

> Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

@zimlu02 may wants to check if this is the case currently - as we only have the binary redistribution this notice should actually be part of the README (I think that's what one would count as "in the documentation and/or other materials").

**Comment by zimlu02** [comment]
Thank you for your notice.
We have listed antlr4ts Copyright (c) 2016 The ANTLR Project in the LICENSE.md file which contains BSD-3 clause.
Does this address your concern?

Open-sourcing of this project is still under consideration, even though we have closed the previous issue. 
Thank you for your interest!

**Comment by GitMensch** [comment]
At least from the list above (haven't verified that) sinon and d3 are also included in the binary distribution and so far not listed, you may want to recheck that. I did verify that LICENSE.md is also part of the distribution, I'm just not sure if "include a file" counts (I'd _guess_ it does).

**Comment by venkatzhub** [comment]
Hi @OlegKunitsyn - Did you look at this open source project: https://github.com/eclipse/che-che4z-lsp-for-cobol?

The lever and grammar are open sourced as part of that project, and that can be the basis for any additional tools around Enterprise COBOL eco-system. 

This project uses the COBOL LSP as  the base, and provides additional functionality, but the actual grammar, lexer, parser are already open sourced via the LSP editor. So I would be curious to know if that would satisfy the need that you are looking for?

**Comment by OlegKunitsyn** [comment]
Of course, I've checked LSP sources (as well as https://github.com/antlr/grammars-v4/) and found
- CobolLexer.g4 copyrighted by Broadcom
- CobolParser.g4 copyrighted by @uwol (https://github.com/uwol/proleap-cobol-parser), without attribution
- these ANTLR files can not be compiled to valid TS without modifications.

Can you upload actual CobolLexer.g4, CobolParser.g4 and /src/extension/antlr-auto-generated files?
This step would help fix LSP base, reward the authors and inspire development of COBOL tools (not only Enterprise ones).
Don't be evil like modern Google. :)

**Comment by venkatzhub** [comment]
@OlegKunitsyn - the intent for open sourcing the COBOL LSP project was indeed to promote/build the eco-system :). With that said, having a good understanding of the use cases or needs would help us do the right thing. This is a great conversation, and we will look into your request, and get back to you. 

Our intent and focus is on IBM Enterprise COBOL, and we will do the right thing to enable, and build that eco-system.

**Comment by zimlu02** [comment]
@OlegKunitsyn we have updated the license in the [new version](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/0.2.0).
Thank you for your notice.

**Comment by imohammednayeem** [comment]
Hi, I am not able to see the option of control flow when I am trying to left-click on a COBOL code

**Comment by GitMensch** [comment]
> Hi, I am not able to see the option of control flow when I am trying to left-click on a COBOL code

That's a totally different issue, please create a new issue for that (and specify your installed extensions and what language-identifier the COBOL code is actually using) and delete the post above here.

**Comment by sundar-sarvam** [comment]
Is there any plans to open-source COBOL control flow? It would really help developers to contribute on top of this by doing repo level graphs, etc.

**Comment by VitGottwald** [comment]
Hello @sundar-sarvam . At the moment we do not plan to open source CCF. But it would help us to understand what are the things you are interested in from the CCF perspective to have a discussion about it.

Which part of CCF is interesting for you and in case we would open source it are you interested in contributing to it?

- the analysis of paragraph relationships
- the ui for drawing paragraph relationships
- the javascript runtime based COBOL parser (runs in node or a browser, does not require JAVA)

**Comment by sundar-sarvam** [comment]
All of the three are pretty good contributions, with the order being 3>1>2. I can't guarantee I will be able to contribute but will surely discuss with my team and see how can we add value to CCF but we would love to use it ourselves and tinker with it for now.

**Comment by VitGottwald** [comment]
Thank you for the clarification I will take it back for a discussion. Even though the extension is not open source at the moment, it is freely available from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.ccf) and from the [Open VSX](https://open-vsx.org/extension/BroadcomMFD/ccf). You can tinke with it and let us know what you think. And if you find any issues feel free to report them.

**Comment by sundar-sarvam** [comment]
True @GitMensch. Contributing to CALL statements can be done once when the CCF is open-sourced. @VitGottwald I have been using CCF for sometime from VSC and I love it absolutely. I like to see a lot of feature additions which are currently missing like CALL maps, etc. which the open-source community will help with if CCF is open-sourced. Please consider the overwhelming request.

**Comment by VitGottwald** [comment]
Thank you for the input @sundar-sarvam and @GitMensch . I suggest you join our [Code4z Slack](https://join.slack.com/t/che4z/shared_invite/zt-22b0064vn-nBh~Fs9Fl47Prp5ItWOLWw) where you can watch for latest announcements. You can also get in direct touch with us there. Should you choose to join the Code4z Slack, please, ping me there.
