### ISSUE TITLE
Not able to see 'Generate COBOL Control Flow'

### ISSUE THREAD

**Issue by imohammednayeem** [BroadcomMFD/cobol-control-flow#14]
Hi,
When I am doing a left-click on .CBL file, I am unable to see the 'Generate COBOL Control Flow' option. I have installed the 'COBOL Control Flow 0.2.0' extension in Visual studio

**Comment by ishche** [comment]
Hello!

Thank you for the feedback!
Do you have IBM Z Open Editor installed?
Could also try to call "Generate COBOL Control Flow" through command palate.
To do it press F1 and type "Generate COBOL Control Flow". If there will be a command available, please execute it.

**Comment by imohammednayeem** [comment]
Yes IBM Z open editor is installed, and yes I can now do it thru command palate. thanks

**Comment by zimlu02** [comment]
Hi Mohammed,

it is a known issue that different COBOL editors [interferes each other](https://github.com/IBM/zopeneditor-about/issues/70). To avoid such conflicts it is suggested to use editors from one publisher and disable others. At this moment COBOL Control Flow is optimized only for [COBOL Language Support plugin](https://open-vsx.org/extension/BroadcomMFD/cobol-language-support).

**Comment by zimlu02** [comment]
This problem should be no longer present in the latest version. 
Closing the issue.
