### ISSUE TITLE
Duplicate or conflicting functionality

### ISSUE THREAD

**Issue by m0rph84** [BroadcomMFD/cobol-control-flow#16]
When installed along with '[COBOL Source editing Bitlang](https://marketplace.visualstudio.com/items?itemName=bitlang.cobol)' plugin, I got the following error:

> The extension ccf from BroadcomMFD has conflicting functionality
> Id: BroadcomMFD.ccf
> Description: Extension for cobol control flow
>  Version: 0.2.0
> Repository: https://github.com/BroadcomMFD/cobol-control-flow
> Bug Reporting: https://github.com/BroadcomMFD/cobol-control-flow/issues
> Reason: **debugger support is problematic with this extension**

**Comment by zimlu02** [comment]
Hi Luca,

yes, different COBOL editors may interfere with each other. At this time we only focus to optimize CCF plugin with [COBOL LS](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support) extension.

**Comment by m0rph84** [comment]
Ok, thank you for your reply.

**Comment by zimlu02** [comment]
No problem. If you agree I am closing this issue.
Thank you

**Comment by GitMensch** [comment]
Why should debugger support be problematic with the other extension? Are there any insights about that?

**Comment by zimlu02** [comment]
I believe this message came from Bitlang extension but I cannot replicate it anymore. Can you?
