### ISSUE TITLE
CCF - cannot read property analysis error

### ISSUE THREAD

**Issue by db671543** [BroadcomMFD/cobol-control-flow#20]
Using Zowe explorer and opening PARTSUPP ... I get the following error and CCF is not created
![2021-06-11_12-12-13](https://user-images.githubusercontent.com/57908777/121671164-8639fe80-caae-11eb-971e-432c2a11f05d.png)

**Comment by db671543** [comment]
I found the problem ... I had to go and select a startup folder and after that things worked

**Comment by zimlu02** [comment]
Reopening the ticket, this situation should be handled with a better notification message, instructing the user to open the workspace...

**Comment by nalmabrcom** [comment]
The same behavior is for E4E + CCF.

**Comment by zimlu02** [comment]
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/957

**Comment by zimlu02** [comment]
This issue has been addressed in the [latest 0.4.1 release](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/0.4.1). Please feel free to reopen the ticket if your problems persist.
