### ISSUE TITLE
CCF having an issue with NUM(  ) COBOL function 

### ISSUE THREAD

**Issue by venkatzhub** [BroadcomMFD/cobol-control-flow#22]
In some cases, constructs like NUM() are causing the CCF to not display a paragraph that contains it, as probably those constructs are not being parsed by the restricted CCF grammar.

**Comment by zimlu02** [comment]
Fixed in the 1.0.1 release.
https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.1
