### ISSUE TITLE
Two or more CBL cards at begining of source ==> index parameter must be between >= 0 and <= number of children.

### ISSUE THREAD

**Issue by FALLAI-Denis** [BroadcomMFD/cobol-control-flow#23]
When more than one CBL card is present at the start of the source code, the Cobol Control Flow extension triggers an error when generating the graph.

No CBL card:
![20210620-CCF01](https://user-images.githubusercontent.com/63861965/122674081-dfeba880-d1d3-11eb-9406-89e4bd45a356.png)

Only one CBL card:
![20210620-CCF02](https://user-images.githubusercontent.com/63861965/122674086-e4b05c80-d1d3-11eb-8836-b69530c6d699.png)

Two CBL cards:
![20210620-CCF03](https://user-images.githubusercontent.com/63861965/122674089-e8dc7a00-d1d3-11eb-9bfa-8d7ecca99498.png)

**Comment by FALLAI-Denis** [comment]
Hi,

The problem is still present in version 0.4.1.
Only the error message differs:

![image](https://user-images.githubusercontent.com/63861965/156716448-f730aa72-66f1-41a4-9795-cca77dd8ae16.png)

Without the 2 CBL cards at the start of the source code, the graph is displayed correctly.

**Comment by zimlu02** [comment]
Hi Denis,
this should be fixed in the latest 1.0.1 release. Please re-open the ticket, if the fix won't work for you.
https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.1
Thank you!
