### ISSUE TITLE
Compiler directives in source ==> various problems

### ISSUE THREAD

**Issue by FALLAI-Denis** [BroadcomMFD/cobol-control-flow#24]
In the presence of compilation directives in the source code, the Cobol Control Flow extension triggers various anomalies.

![20210620-CCF04](https://user-images.githubusercontent.com/63861965/122674617-42de3f00-d1d6-11eb-8e84-b4da2bf6fdd1.png)

![20210620-CCF05](https://user-images.githubusercontent.com/63861965/122674474-afa50980-d1d5-11eb-8d63-5011e1cd10b7.png)

![20210620-CCF06](https://user-images.githubusercontent.com/63861965/122674478-b3d12700-d1d5-11eb-9f56-1b3adcdcce80.png)

**Comment by zimlu02** [comment]
Hi Denis, could you please confirm whether the [latest 0.4.1 release](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/0.4.1) fixes your issue? Thank you.

**Comment by FALLAI-Denis** [comment]
Hi @zimlu02 

![image](https://user-images.githubusercontent.com/63861965/156571435-594ed879-3139-471a-a77e-7f62113f0215.png)

We do not use Broadcom's "COBOL Language Support" extension, but that of another vendor.

**Comment by zimlu02** [comment]
That is still OK, you don't necessarily have to use COBOL LS. This message only indicates that the file contains too many syntactic errors, that CCF parser cannot build a  meaningful graph. 
The syntax awareness tool such as COBOL LS or others may just help you to identify syntax problems in the code...

**Comment by FALLAI-Denis** [comment]
Hi,

The problem is still present in version 0.4.1.
Only the error message differs:

![image](https://user-images.githubusercontent.com/63861965/156717002-5ba28ede-41b9-41a2-aa5f-074861bade2b.png)

Without compilation directives in source code, the graph is displayed correctly.

**Comment by FALLAI-Denis** [comment]
Hi, 

For information, version 1.0.2 of CCF seems to have fixed some problems that we encountered with the structure of our COBOL code.

Now the graph is displayed correctly and corresponds to the structure of our program.
Moreover, CCF works with another COBOL code editor extension than "COBOL Language Support", **which is a real satisfaction for us**.

**Thanks to the CCF teams for the work done.**

We still have to validate the operation of CCF on other use cases, and if all goes well, CCF will become one of the major bricks of our new COBOL Development Workshop.

![image](https://user-images.githubusercontent.com/63861965/176842252-b1d6947b-86ba-4d96-8c5b-91ca98ca7be8.png)

![image](https://user-images.githubusercontent.com/63861965/176842547-bdce90eb-3819-40a2-96d0-d8701c1ed48b.png)

![image](https://user-images.githubusercontent.com/63861965/176842640-3fae7cb5-f4f9-4e67-b15c-75aba80ff881.png)

**Comment by zimlu02** [comment]
Hi Denis,

we are very happy this version works for you! 
Can I close this issue? 
Please if needed open new issues for your other use cases. 
Thank you.

**Comment by FALLAI-Denis** [comment]
Yes !
