### ISSUE TITLE
Cobol coded with SECTION not recognized 

### ISSUE THREAD

**Issue by niromon-dev** [BroadcomMFD/cobol-control-flow#25]
Hi,
We are giving a try to your plugin but it sems not working properly with the code base we have.
The code use a lot of Cobol section. Is there any workaroud to make it works ?

Thanks a lot !

Arnaud

**Comment by venkatzhub** [comment]
@niromon-dev - Can you provide a simple example of the COBOL source you are trying to invoke the Control flow on? Just want to understand the structure of the COBOL sections being used.

**Comment by niromon-dev** [comment]
It seems that it is not the SECTION keyword which cause the issue it is more the CONTINUE Keyword.
For instance If we have 
![image](https://user-images.githubusercontent.com/72360055/124100308-aa11b400-da5e-11eb-8dde-586eacd6ad19.png)
The D1-DISPLAY-TEST node won't be displayed in the graph.
If we transform with 
![image](https://user-images.githubusercontent.com/72360055/124100470-c9a8dc80-da5e-11eb-97ce-10aaa0913575.png)
It will be displayed.
Here are the 2 files : [test.zip](https://github.com/BroadcomMFD/cobol-control-flow/files/6747030/test.zip)

**Comment by FALLAI-Denis** [comment]
Also problems with "exit section" / "exit paragraph".

**Comment by zimlu02** [comment]
Fixed in the latest 1.0.1 release. Please re-open the ticket, if the fix won't work for you.
https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.1
Thank you!
