### ISSUE TITLE
Cannot read property 'location' of undefined

### ISSUE THREAD

**Issue by RodrigoDornelles** [BroadcomMFD/cobol-control-flow#27]
I don't know why this happens, but if I "simplify" the Cobol dialect works, I tested it in this code https://github.com/psywave-games/pong-cobol/blob/master/game.cbl

Maybe related #20
![Screen Shot 2021-10-18 at 20 55 16](https://user-images.githubusercontent.com/29123479/137821868-1a1667cd-e923-4e1b-84b3-190b47e0d028.png)

**Comment by FALLAI-Denis** [comment]
maybe related #24

**Comment by GitMensch** [comment]
Not sure if it is the same issue - getting "Cannot read property 'type' of undefined".
In any case it would be good to have an actual "full" error message (stacktrace?) in the Output pane under "Extensions" to get a better clue what is happening.

**Comment by zimlu02** [comment]
In progress and should be fixed in the next release.

**Comment by zimlu02** [comment]
This issue has been addressed in the [latest 0.4.1 release](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/0.4.1). Please feel free to reopen the ticket if your problems persist.
