### ISSUE TITLE
Error Message: Failed to generate flow

### ISSUE THREAD

**Issue by jellypuno** [BroadcomMFD/cobol-control-flow#3]
I am experiencing this error when I try to:
1) use the extension to a large COBOL file that has 38k lines of code. 
2) open an small COBOL file that has invalid parameters like the image below but it should be fine because the procedure division is okay.

![image](https://user-images.githubusercontent.com/45042840/89644727-c93cab80-d8b8-11ea-970e-89ac184a3cd4.png)

I am not sure what the problem with the 2 scenarios. The error message is too generic.

**Comment by vibhor-bc** [comment]
@jellypuno 

The logs can be accessed via the developer tools -
1). Open the COBOL file for analysis.
2). Ctrl + Shift + P
3). Type "Developer:Toggle Developer Tools"
4). Go to console tab and clear any existing logs.
5). Hit "View COBOL Control Flow".
6). If the analysis fails , you should be able to see the logs in red.

If you can share the logs here ?

**Comment by jellypuno** [comment]
Log for First Program with invalid values:

![image](https://user-images.githubusercontent.com/45042840/89655029-cd24f980-d8c9-11ea-8a8e-fa66b89c87dd.png)

**Comment by jellypuno** [comment]
Log for Second Program without invalid values

![image](https://user-images.githubusercontent.com/45042840/89655133-ed54b880-d8c9-11ea-899f-2022bde6b5a8.png)

**Comment by vibhor-bc** [comment]
Thanks for providing the logs. Does the COBOL files pass syntax validation with other extensions ? 
Post clicking on generate flow , roughly after how much time do you see the error with the 38k file ?

**Comment by jellypuno** [comment]
> Does the COBOL files pass syntax validation with other extensions ?

It does but it has missing copybooks.

> roughly after how much time do you see the error with the 38k file ?

Around 2 seconds. This is the log for the 38k lines COBOL program

![image](https://user-images.githubusercontent.com/45042840/89656741-4887aa80-d8cc-11ea-9eb8-a990ddbcbc95.png)

**Comment by venkatzhub** [comment]
@jellypuno - for the file with the invalid characters - the logic is parsing the whole file - not just the procedure division, so what you are seeing is expected.

**Comment by petevick** [comment]
I am getting errors for things that are valid in HP Cobol - EG


![image](https://user-images.githubusercontent.com/3090373/92733362-84041180-f36f-11ea-84cf-fbb2a8b70023.png)

Flags these 4 lines as invalid
001000$VERSION "Version ECOMETRYRev4110:36A"
001100$DEFINE %VERSION=
001200    " <<VERSION 101A "WHEN-COMPILED ">> "#
001300$CONTROL USLINIT,NOSOURCE,NOCROSSREF

Flags anything with a %
018900 01  FILESESS.
019000     05 FILLER               PIC X(13) VALUE "FILE SHMEFILE".
019010     05 FILLER               PIC X(08) VALUE ";REC=-80".
019400     05 FILLER               PIC X VALUE %15.
018900 01  SHOWSESS.
019000     05 FILLER               PIC X(16) VALUE "SHOWME>*SHMEFILE".
019400     05 FILLER               PIC X VALUE %15.
018900 01  OUT-EQUATE.
019000     05 FILLER               PIC X(15) VALUE "FILE ITMSOUT = ".
019100     05 OUT-FILE.
019200        07 FILLER            PIC X(3) VALUE "KOT".
019300        07 OUT-TIME          PIC X(5).
019400     05 FILER                PIC X VALUE %15.

Flags anything with \\
749000     CALL INTRINSIC 'WHO' USING \\, \\, \\, USER-ID,
749010                                \\, \\, \\, TERM-IDC.
055600     MOVE "ITMREPRT"                TO CODE-NAME.


Thanks

**Comment by venkatzhub** [comment]
@petevick - The extension supports IBM Enterprise COBOL syntax only. I noticed that we do not state that explicitly. We will update the extension description to state that.

**Comment by petevick** [comment]
OK - Thanks  :(

**Comment by GitMensch** [comment]
I see the same issue with `COPY`books, the log says:

```
console.ts:137 [Extension Host] line 87:11 mismatched input 'COPY' expecting {<EOF>, CBL, CONFIGURATION, DATA, END, ID, IDENTIFICATION, INPUT_OUTPUT, PROCEDURE, PROCESS, SPECIAL_NAMES}
t.log @ console.ts:140
$logExtensionHostMessage @ mainThreadConsole.ts:29
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:444
_receiveMessage @ ipc.net.ts:782
(anonymous) @ ipc.net.ts:639
fire @ event.ts:584
acceptChunk @ ipc.net.ts:198
(anonymous) @ ipc.net.ts:198
t @ ipc.net.ts:27
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
notificationsAlerts.ts:40 Failed to generate flow
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
notify @ notificationService.ts:88
(anonymous) @ mainThreadLogService.ts:16
_showMessage @ mainThreadLogService.ts:16
$showMessage @ mainThreadLogService.ts:16
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:444
_receiveMessage @ ipc.net.ts:782
(anonymous) @ ipc.net.ts:639
fire @ event.ts:584
acceptChunk @ ipc.net.ts:198
(anonymous) @ ipc.net.ts:198
t @ ipc.net.ts:27
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

The COBOL source is:

```cobol
       IDENTIFICATION DIVISION.
       PROGRAM-ID.    TESTME.
       AUTHOR.        THE USER.
      *---------------------------------------------------------------*
      * a lot of comments until line 83
      *-----------------------------------------------------------*
      /
       ENVIRONMENT DIVISION.
           COPY  MYCONF.
      /
       DATA DIVISION.
       WORKING-STORAGE SECTION.
```

That should work, shouldn't it? Is there an option to specify copybook paths?

> The extension supports IBM Enterprise COBOL syntax only.

@venkatzhub That doesn't mean it must keep that restriction in the future, do you agree?

**Comment by venkatzhub** [comment]
@GitMensch - I have tried it with Copy statements, and the Control flow worked when the copybooks were resolved and when not resolved. 

In any case, you can specify the path to copybooks in the VSCode Settings --> Extensions --> Broadcom COBOL LSP. The path can be local i.e for copybooks residing on your workstation or data set names if they are on z/OS. 

To your other question on supporting other syntax than IBM Enterprise COBOL, that is a point in time statement. With that said, there are no current plans to support other dialects. 

#8 is some what related to this, and if there is enough interest, we may decide to open source to allow community to add support for other dialects.

**Comment by GitMensch** [comment]
> In any case, you can specify the path to copybooks in the VSCode Settings --> Extensions --> Broadcom COBOL LSP. The path can be local i.e for copybooks residing on your workstation or data set names if they are on z/OS.

I see - that shows the issue as I don't have Broadcom COBOL LSP installed (it is too mainframe centric for my use), can we have additional (local only) paths in this extension? A "common" user would not need it, but everyone without the Broadcom COBOL LSP has an option to use it.

**Comment by zimlu02** [comment]
As stated, COBOL LS supports also local copybooks, which should solve the original issue.
We will update the CCF documentation to emphasize the benefits of COBOL LS integration. 
If any objection I would close this issue.

**Comment by GitMensch** [comment]
There were multiple issues:

1. The flow cannot be generated if the code contains invalid (or not recognized) COBOL (as seen in the picture there were place holders, but the "structure" (`DIVISION`s, SECTION`s) is correct - an approach to skip all things from the first unrecognized character(here a  `{`) to the next line (keeping the line as an "error" token, if necessary) or until the next valid line is found would help with this (this part may be moved out to a different issue for clarity).
2. Main issue: Ensure that there is never only a "general" message like "Failed to generate flow" - at least add a note to check details in the log and actually log to the extension host directly (or an own output view) [or at least provide the "how to get the details" part in a wiki entry and reference this in the message].
3. the copybooks - I think that's completely solved with having this "supported by the LSP extension" (which needs some tweaks for copybook extensions and other items, but that's nothing for here - the docs are already fine _now_)
4. support for more COBOL dialects - this would likely be something for the LSP, too - but a "water approach" to just skip the not recognized lines as outlined in 1 would solve most of this for CCF, too.

I'd suggest to possibly move 1 out to a new issue, ignore 3+4 in here and keep this issue open until 2 is solved.

**Comment by zimlu02** [comment]
Hi @GitMensch,

we have improved the CCF messages in the latest [release](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.2). Could you give it a try and share with us your thoughts?

Regarding your point 1) the current strategy is that we inform the user about the syntax errors causing the graph may be inaccurate. If the program contains too many errors though, it makes a little sense still to try to render a graph. Skipping invalid lines may result in a completely misleading graph. Or do I understand your suggestion wrong?

Thank you!
