### ISSUE TITLE
ECCF0002: Flow can be generated only for ...

### ISSUE THREAD

**Issue by GitMensch** [BroadcomMFD/cobol-control-flow#34]
There are at _least_ two more "commonly used" extension names for COBOL on PC: pco and sqb - both for files that need to be run through a SQL preprocessor.
Other than directly adding those two extensions (I guess I'd be able to send a PR for this) I suggest to either drop the file check completely - inspecting whatever the LSP extension does - because this works on those files (possibly because of a file setup in vscode "recognize pco as COBOL files") or making this list an extension setting with the current 3 values ".cob", .cobol, .cbl" as default (this way people that only use cbl can also adjust to look out only for this file extension).

Is there a reason that ccf is not enabled on copybooks? It would be reasonable in this case to start the process at its top (where for multi-section-copybooks the "main" part may be).

**Comment by zimlu02** [comment]
Hi Simon,

this should be addressed in 1.0.3 version. You can try to generate a graph for any file for which you choose the COBOL language ID (for that you need to have installed any COBOL-syntax extension like [COBOL LS](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support) or other).

In case the file is not a valid COBOL or contains too many syntax errors, the graph won't be generated.
I am closing this issue. Please feel free to reopen if the new version doesn't work as you would expected. 
Thank you.

Regarding enabling CCF for copybooks - could you please create a new separate ticket if you would like to have this feature?
There is a faulty behavior now though. I have created a new ticket - https://github.com/BroadcomMFD/cobol-control-flow/issues/45
