### ISSUE TITLE
Flow is generated but not for all 

### ISSUE THREAD

**Issue by zdzuni** [BroadcomMFD/cobol-control-flow#35]
I was installed the plug in in VSCode and tried to generate flow using plug in . Fore code with 23k lines of code I got only the following 

![workflow](https://user-images.githubusercontent.com/34841002/157883706-64c0132c-fec4-4f6f-90bb-9e69f2be12c3.PNG)

The plug in recognizes only few sections for example:
PROCEDURE DIVISION USING 
0-STEUERUNG SECTION.  
EINGANG. 
9-098-TRACE SECTION.  
EINGANG.
AUSGANG.

Could be that a problem due to German language or something else? Java is installed and COBOL Language Support Plug in for VSCode.

**Comment by zimlu02** [comment]
Hello @zdzuni ,
could you please try again with the latest versions of [COBOL Control Flow v1.0.4](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.4) and [COBOL LS v1.1.1](https://github.com/eclipse/che-che4z-lsp-for-cobol/releases/tag/1.1.1)?
We have addressed several issues that should have solved your problem. 
Thank you for any comments.
