### ISSUE TITLE
Failed to load active editor

### ISSUE THREAD

**Issue by zdzuni** [BroadcomMFD/cobol-control-flow#36]
Hi,
I am giving a try to get flow using your plugin, but it seems not working properly with the code base I have.
For almost 22k LoC I get only one flow:
![Cobol Flow Control](https://user-images.githubusercontent.com/34841002/158163652-7c565720-021d-4b47-88df-9e43ea19aa65.PNG)

I have also installed the following Plugins: **IBM Z Open Editor** and **Language Support** 

When I try to call "**Generate COBOL Control Flow**" through command palate, I got an error:

`Failed to load active editor`

Is there something wrong with code structure or with Plug In configuration?
Thanks a lot !

**Comment by niharikasw91** [comment]
@zdzuni, Thank you for your feedback.

I have tried to reproduce the issue with IBM Z Open editor and Language Support installed and I do not get any error. Here are the versions of the following plugins that I am using:

Cobol control flow - v.0.4.1
Ibm z open editor - v1.4.1
Cobol LS - v0.21.0+development.931
Vscode - 1.65.2

Please check the "Problems" tab for any error. If you do not see any error, is it possible for you to share the source file after cleaning any confidential data.

Thank you !

**Comment by zimlu02** [comment]
Fixed in [v.1.0.6](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v.1.0.6)
