### ISSUE TITLE
Consider EXEC CICS RETURN as end of program

### ISSUE THREAD

**Issue by FALLAI-Denis** [BroadcomMFD/cobol-control-flow#38]
Hi,

In a CICS program, it is the EXEC CICS RETURN statement that terminates the program, and in principle the COBOL GOBACK instruction is absent from the program.

CCF does not treat the EXEC CICS RETURN command as an end of program sequence and as a result the graph is badly constructed.

With EXEC CICS RETURN and with goback:

![image](https://user-images.githubusercontent.com/63861965/177189088-7efa3e6f-d7b2-4e43-8806-6b9a312f3867.png)

With EXEC CICS RETURN and without goback:

![image](https://user-images.githubusercontent.com/63861965/177189349-4960760e-58a1-4ac4-8ee2-3220fa502f05.png)

**Comment by FALLAI-Denis** [comment]
See also the case of EXEC CICS XCTL which is also a sequence break identical to a GO TO COBOL instruction.

EXEC CICS LINK is equivalent to a CALL COBOL statement.

**Comment by zimlu02** [comment]
Hi Denis,
this issue should be fixed in [v1.0.4.](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.4)
