### ISSUE TITLE
CCF issue with Gen/Cobol

### ISSUE THREAD

**Issue by Tele64now** [BroadcomMFD/cobol-control-flow#40]
Here's the email from the Endevor Support Engineer at Travelers.

We are on Java 8+.  Control Flow runs all of the time, it’s just that some of the time it produces bad results.

 

The 2 examples we have are:

The chart skips much of the program. Our example seems to see the initialization read of the input file, decide it is at end-of-file, and then skip straight to termination.
A large (12,000 lines) CoolGen program. Clicking on a paragraph bubble in the flow chart is supposed to bring you to that paragraph in the source code. Instead it brings you someplace nowhere close.   
 

Marc A Hanna

HSCM Support (Endevor)

 I've opened this issue on behalf of Travelers.
Feel free to contact me at "milton.hustonjr@broadcom.com"

Regards,

Milt

**Comment by niharikasw91** [comment]
@Tele64now 
Hi Milton, hope you are doing well.

Thank you for bringing the issue to our notice. I will be assisting you for this case. 

To proceed with the issue, we request you to kindly share the source code file over the email by removing ay sensitive data. It can really help us to reproduce the issue and find the solution at the earliest. 

Please also check with the engineer if they also use COBOL Language Support extension.

**Comment by zimlu02** [comment]
Fixed in [v1.0.4](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.4)
