### ISSUE TITLE
"exit section" is a statement, not a section label

### ISSUE THREAD

**Issue by FALLAI-Denis** [BroadcomMFD/cobol-control-flow#44]
Hi,

Since version 1.0.3, statements "exit section" are reported in CCF graph as labels. That's wrong.

"exit section" are statements, as "exit paragraph", or "exit perform" and they are written un marge B (columns 12 thru 72), not un marge A (columns 8 thru 11).

We use "perform section-from thru section-to" statements, and the "section-to" contains only an "exit section" statement.

In version 1.0.3 the CCF graph became unreadable due to the processing error on the "exit section" instructions.

CCF must only take into account for the labels the information which begins in margin A, that is to say between columns 8 and 11.

![image](https://user-images.githubusercontent.com/63861965/197134906-32ffa031-ef75-4a3f-82ed-2f8dc46cae68.png)

Same graph program with CCF 1.0.2:

![image](https://user-images.githubusercontent.com/63861965/197136019-67248fd9-3aa5-4b32-9074-308eec8f6d2f.png)

In version 1.0.3, the "label-to" labels are displayed in graph whereas they were not in version 1.0.2: OK.
But the "exit section" statements must not appear in the graph.
We also see links between these "exit section" statements and other labels which a priori have no reason to exist.

Use case program:
[S91100.cbl.txt](https://github.com/BroadcomMFD/cobol-control-flow/files/9836699/S91100.cbl.txt)

**Comment by zimlu02** [comment]
Thank you @FALLAI-Denis for reporting this issue. We will address it in the next release.

**Comment by zimlu02** [comment]
Hi Denis,
this issue should be fixed in [v1.0.4.](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.4)
