### ISSUE TITLE
EXIT SECTION causes graph to end instead of continue.

### ISSUE THREAD

**Issue by ekuether** [BroadcomMFD/cobol-control-flow#48]
Issue:

Putting an EXIT SECTION instead of just an EXIT will cause the graph to stop looking at the rest of the program.

Example Code:

       IDENTIFICATION DIVISION.
       PROGRAM-ID. HLLOWRLD
       DATA DIVISION. 

       WORKING-STORAGE SECTION. 
       01  USRNAME           PIC X(10).

       PROCEDURE DIVISION.
       0000-MAIN SECTION.
           PERFORM 1000-GET-NAME
           PERFORM 2000-TEST
           DISPLAY 'HELLO 'USRNAME
           GOBACK
           .
       1000-GET-NAME SECTION.
           ACCEPT USRNAME.
           PERFORM 1000-EXIT.
       1000-EXIT.
           EXIT SECTION.
       2000-TEST SECTION.
           PERFORM 2000-EXIT.
       2000-EXIT.
           EXIT SECTION.

Example Graph

![image](https://user-images.githubusercontent.com/96203346/215492464-334ae1fb-2db2-4c22-850c-3ca65f4cb7bf.png)

Comments:

Notice how we perform both 1000-GET-NAME and 2000-TEST, but only 1000-GET-NAME is shown on the graph

**Comment by zimlu02** [comment]
Fixed in [v1.0.5](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v.1.0.5) release.
