### ISSUE TITLE
Differing Graph based on SECTION 

### ISSUE THREAD

**Issue by ekuether** [BroadcomMFD/cobol-control-flow#49]
Example Code:

Code 1:

       IDENTIFICATION DIVISION.
       PROGRAM-ID. HLLOWRLD
       DATA DIVISION. 

       WORKING-STORAGE SECTION. 
       01  USRNAME           PIC X(10).

       PROCEDURE DIVISION.
       0000-MAIN SECTION.
           PERFORM 1000-GET-NAME
           PERFORM 2000-TEST
           DISPLAY 'HELLO 'USRNAME
           GOBACK
           .
       1000-GET-NAME.
           ACCEPT USRNAME.
           PERFORM 1000-EXIT.
       1000-EXIT.
           EXIT.
       2000-TEST.
           PERFORM 2000-EXIT.
       2000-EXIT.
           EXIT.

Graph 1:

![image](https://user-images.githubusercontent.com/96203346/215493274-ada23911-6a51-4431-bf59-90a2728cf12d.png)

Code 2:

       IDENTIFICATION DIVISION.
       PROGRAM-ID. HLLOWRLD
       DATA DIVISION. 

       WORKING-STORAGE SECTION. 
       01  USRNAME           PIC X(10).

       PROCEDURE DIVISION.
       0000-MAIN SECTION.
           PERFORM 1000-GET-NAME
           PERFORM 2000-TEST
           DISPLAY 'HELLO 'USRNAME
           GOBACK
           .
       1000-GET-NAME SECTION.
           ACCEPT USRNAME.
           PERFORM 1000-EXIT.
       1000-EXIT.
           EXIT.
       2000-TEST SECTION.
           PERFORM 2000-EXIT.
       2000-EXIT.
           EXIT.

Graph 2:

![image](https://user-images.githubusercontent.com/96203346/215493561-5c43bccb-d7fb-4583-800c-6cfc7d14620c.png)

Issue:

Notice how the only difference between the first code and the second code is that "SECTION" is put after 1000-GET-NAME and 2000-TEST. Both codes exit regardless and will function the same way, however the graph is different between the two.

**Comment by ekuether** [comment]
Another Example of SECTION and Graphing:

### Code:

       IDENTIFICATION DIVISION.
       PROGRAM-ID. HLLOWRLD
       DATA DIVISION. 

       WORKING-STORAGE SECTION. 
       01  USRNAME           PIC X(10).

       PROCEDURE DIVISION.
       0000-MAIN SECTION.
           PERFORM 1000-GET-NAME
           PERFORM 2000-TEST
           PERFORM 3000-TEST
           DISPLAY 'HELLO 'USRNAME
           GOBACK
           .
       1000-GET-NAME SECTION.
           ACCEPT USRNAME.
           PERFORM 1000-EXIT.
       1000-EXIT.
           EXIT.
       2000-TEST.
           PERFORM 2000-EXIT.
       2000-EXIT.
           EXIT.
       3000-TEST SECTION.
           PERFORM 3000-EXIT.
       3000-EXIT.
           EXIT.

### Graph

![image](https://user-images.githubusercontent.com/96203346/215498763-8ddefa1c-1b5f-437d-93ba-da0fda82fe75.png)

**Comment by sergiuilie** [comment]
closing and opening a  [new issue](https://github.com/BroadcomMFD/cobol-control-flow/issues/51) that is directly impacting this issue
