### ISSUE TITLE
A procedure was not detected

### ISSUE THREAD

**Issue by jellypuno** [BroadcomMFD/cobol-control-flow#5]
The WRITE-HEADERS is not part of the initial procedures connected to PROCEDURE DIVISION.

The correct flow should be:
1. OPEN FILES
2. **WRITE HEADERS**
3. READ NEXT RECORD
    A. READ RECORD
    B. WRITE RECORD
         i. WRITE HEADERS (If Report Page Break)
4. WRITE TRAILERS
5. CLOSE STOP 

![image](https://user-images.githubusercontent.com/45042840/89649253-bcbc5100-d8c0-11ea-988e-4b1cc9d2b1f0.png)

**Comment by jellypuno** [comment]
Additional issues on procedures

1. EXIT PARAGRAPH was considered a separate procedure
2. The variables after the EXIT PARAGRAPH was considered a procedure as well 

![image](https://user-images.githubusercontent.com/45042840/89654532-145eba80-d8c9-11ea-9332-f4ecea06adcf.png)

**Comment by Nurkambay** [comment]
This bug should be split into 2 parts at least. Also, before building a graph you must resolve all errors first. Otherwise, no guarantee that graph will be relevant :-)

**Comment by Nurkambay** [comment]
@jellypuno yep, that's why it is a bug. It is fixed now. Another issue is that If you have a significant error in the COBOL code you will not see anything relevant to the real CCF graph :-( And it is another issue that must be fixed on the COBOL LS side

**Comment by zimlu02** [comment]
Fixed in the 1.0.1 release.
https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v1.0.1
