### ISSUE TITLE
Support 'GOBACK' statement 

### ISSUE THREAD

**Issue by sergiuilie** [BroadcomMFD/cobol-control-flow#51]
The graph is generated despite the fact that in the code, the **'GOBACK'** statement is used, and statements following it are not executed.

Example:
```
   IDENTIFICATION DIVISION.
   PROGRAM-ID. HLLOWRLD
   DATA DIVISION. 

   WORKING-STORAGE SECTION. 
   01  USRNAME           PIC X(10).

   PROCEDURE DIVISION.
   0000-MAIN SECTION.
       PERFORM 1000-GET-NAME
       PERFORM 2000-TEST
       DISPLAY 'HELLO 'USRNAME
       GOBACK
       .
   1000-GET-NAME.
       ACCEPT USRNAME.
       PERFORM 1000-EXIT.
   1000-EXIT.
       EXIT.
   2000-TEST.
       PERFORM 2000-EXIT.
   2000-EXIT.
       EXIT.
```

Output:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/23320888/223821965-2efbbb83-473c-434e-ba52-65cc7a0c7a5b.png">

Therefore in the above-mentioned example, the arrow pointing from `1000-EXIT` to `2000-TEST` should not exist due to the **'GOBACK'** statement interrupting the program in the `0000-MAIN SECTION`

**Comment by FALLAI-Denis** [comment]
Hi @sergiuilie,

"Export to JSON" of your sample:

```
[
  {
    "name": "HLLOWRLD",
    "children": [
      {
        "name": "0000-MAIN",
        "children": [
          {
            "name": "1000-GET-NAME",
            "children": [
              {
                "name": "1000-EXIT",
                "children": [
                  {
                    "name": "2000-TEST",
                    "children": [
                      {
                        "name": "2000-EXIT",
                        "children": []
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "name": "2000-TEST",
            "children": []
          }
        ]
      }
    ]
  }
]
```

See [Export CCF Graph to JSON - Missing menu?](https://github.com/BroadcomMFD/cobol-control-flow/issues/55)

**Comment by zimlu02** [comment]
Fixed in [v.1.0.6](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v.1.0.6)
