### ISSUE TITLE
Support for "exit paragraph" statement

### ISSUE THREAD

**Issue by FALLAI-Denis** [BroadcomMFD/cobol-control-flow#53]
Hi,

It seems that CCF does not understand the COBOL `exit paragraph` statement.

![image](https://github.com/BroadcomMFD/cobol-control-flow/assets/63861965/393e97df-fd0e-4510-a209-3b26e713dba3)

Consequence: part of the graph is missing.

The `exit paragraph` statement does not have the same behavior at runtime as the `exit` statement (just like the `exit section` statement, but this is well recognized by CCF).

Thanks.

**Comment by GitMensch** [comment]
Should both `exit paragraph` and `exit section` create a node in the CCF (I'd tend to say "make that configurable")?

**Comment by zimlu02** [comment]
Fixed in [v.1.0.6](https://github.com/BroadcomMFD/cobol-control-flow/releases/tag/v.1.0.6)
