### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [BroadcomMFD/cobol-control-flow#7]
https://open-vsx.org/?search=broadcom lists 5 extensions while https://marketplace.visualstudio.com/publishers/broadcomMFD lists 10 extensions. This extensions (and 4 others) are missing.

Update 2020-12-01: currently 6 vs. 11 extensions listed

As the namespace is already registered and extensions are published this is likely not needed, but it cannot harm: 
Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by zimlu02** [comment]
> https://open-vsx.org/?search=broadcom lists 5 extensions while https://marketplace.visualstudio.com/publishers/broadcomMFD lists 10 extensions. This extensions (and 4 others) are missing.
> 
> As the namespace is already registered and extensions are published this is likely not needed, but it cannot harm:
> Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

Hello, thank you for this idea! 
Is there any particular reason why you would prefer having extensions on OPEN VSX Registry? Maybe related to the IDE you are using?

**Comment by GitMensch** [comment]
I use VSCodium and Theia and both use the Open VSX Registry which only hosts open-source extensions which is exactly what I want to use.

**Comment by zimlu02** [comment]
currently, we're blocked with publishing on Open VSX:
https://github.com/eclipse/openvsx/issues/204 #

**Comment by GitMensch** [comment]
@zimlu02 thank you for the update. Does this only applies to cobol-control-flow or also to the other 4 "missing" extensions?

**Comment by zimlu02** [comment]
I have uploaded all the missing extensions. Thanks for this request!
