### ISSUE TITLE
Where's the actual code?

### ISSUE THREAD

**Issue by GitMensch** [BroadcomMFD/cobol-control-flow#8]
This repo only contains documentation and the samples - Where is the code to be found?

**Comment by venkatzhub** [comment]
@GitMensch - This extension is not open sourced. If there are good reasons (like extending or contributing) that would help form a community around it, we can discuss that possibility. 

Do you have any specific cases for needing access to source?

**Comment by GitMensch** [comment]
> Do you have any specific cases for needing access to source?

Yes, part of these:

* I can inspect what the extension actually does (and so pass a security check more easy)
* I can be quite sure that the extension work also in the future - even if vscode changes needs changes in the extension and the original authors don't do any thing about this issue for whatever reason
* I actually have at least the option to contribute (one thing that _seems_ not to be covered well for example are `SECTION`s and reasonable issues like `CALL` are already reported)
* the extension has the option to be uploaded to the open vsx registry

... actually I try to not waste any time with closed-source programs or extensions.

**Comment by petevick** [comment]
Would like to extend it to work with HP COBOL as it would be really useful. 
Alternately, cater for $ in character 7, % in Working-Storage and \ in Procedure Division. 
Or somehow make that configurable?

Thanks

Pete

**Comment by petevick** [comment]
I have that, and have adjusted it to support some of the HP Stuff. I was particularly interested in yours as I am looking at taking over a project where I don't know the system, so the control flow diagrams would have been useful.

I think I know what it is choking on, which is as I say, $ in char 7, % signs in WS section which are used as control characters, and \\ characters in the Procedure division, that are used as empty parameters.

Thanks

**Comment by GitMensch** [comment]
@petevick could you please check if the bitlang.cobol plugin handles the HP stuff well enough to use it for editing and symbol lookup? if not then I'm sure that a PR to fix that would be welcomed. It would be marvelous if you could throw some of those HP COBOL sources also at the free GnuCOBOL compiler and report there issues you directly see (there are also control flow diagrams available with GC, generated from run-time if you could it getting to run).

@venkatzhub as the issue is not closed I still hope that you may open-source this extension to be usable (and hackable for other dialects that you personally may not care) in general.

**Comment by petevick** [comment]
The bitlang.cobol plugin handles the HP Cobol syntax perfectly. I have a snippet to add some HP specific syntax that I add to the snippet file.
It handles the $ in column 7, the % in working storage, and the \\ in procedure division.

Tried GnuCobol - it doesn't like the $ in 7, % in WS and doesn't support HP Copylibs

Thanks

**Comment by GitMensch** [comment]
Ping @venkatzhub @zimlu02

> as this issue was not closed, I still hope that you may open-source this extension to be usable (and hackable for other dialects that you personally may not care) in general.

If you come to the conclusion that you don't want this: please close both this issue and #7.

**Comment by zimlu02** [comment]
We came to the conclusion that for the time being, we won't open-source this project. 
Thank you for your interest in contribution though.

**Comment by GitMensch** [comment]
> We came to the conclusion that for the time being, we won't open-source this project.

That's sad as I think there's already a bunch of open requests that people could PR changes in (like adding settings with copybook paths, file extensions, parser extensions, ...) - and even if you deem some not "match" to this extension it would still alow a fork that for example, also supports different COBOL dialects.

**Comment by petevick** [comment]
We came to the conclusion that for the time being, we won't open-source this project.
Thank you for your interest in contribution though.

I agree - I would love to add paths for copybook paths, as the source I am working with uses copybooks EVERYWHERE :) 

Again - if you ever change that policy please drop a note here.

Thanks
