### ISSUE TITLE
Support other file extensions such as '.src'

### ISSUE THREAD

**Issue by ChubongaGithub** [BroadcomMFD/cobol-control-flow#9]
Hello,

Any way to recognize other file extensions (such as .src)?

**Comment by vibhor-bc** [comment]
At present there is no support for .src file extensions. Please refer to [supported file extensions](https://github.com/BroadcomMFD/cobol-control-flow#supported-file-types). In case there is COBOL file with .src extension , renaming it to one of the supported file extensions should work.

**Comment by GitMensch** [comment]
Can you please reopen this as feature request and add a setting for that to this extension (defaulting to the current list and possibly the common "cpy")?
